language: cpp

os:
  - linux

compiler:
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9 libboost-dev qt4-qmake; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ -f /usr/bin/g++ ]]; then sudo rm /usr/bin/g++; fi
  - sudo ln /usr/bin/g++-4.9 /usr/bin/g++
  - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2
  - tar jxf boost_1_57_0.tar.bz2
  - cd boost_1_57_0
  - ./bootstrap.sh
  - sudo ./bjam release install -d0 --with-context --prefix=/usr/local -j4
  - sudo ldconfig

install:
  - cd $TRAVIS_BUILD_DIR/test
  - cp ../include/throw/throw.hpp throw.hpp
  - sed 's|%PREFIX%|TEST|g' -i throw.hpp
  - qmake
  - make

script:
  - cd $TRAVIS_BUILD_DIR/test
  - ./test
